HorlogeSkynet/archey4

- archey
See issue #10 for details
Comments are still welcome here
Adds a new entry for hardware temperature
Because it was missing ! And it could be pretty relevant on laptops and Raspberry Pi
On a laptop under Debian, a Raspberry Pi Model B under Arch Linux ARM and a Debian VPS (not detected)
> Adds temperature support

- README.md
- archey
- config.json
Check out the README for the instructions.
> [FEATURE] Adds support for external configuration

- README.md
- archey
- config.json
IPv6 should be supported; and defining the maximum number of LAN addresses can be very useful, if word wrapping is enabled it doesn't look so nice with many addresses.
Both settings are optional features!
> IPv6 support, and maximum number of LAN addresses

- archey
See title
OS handling missing case
By @Si13n7
> Adds support for Windows Subsystem (by @Si13n)

- README.md
I changed the README a little bit to fix typos and make some sentences sound better.
Just to improve the README in general, like make it sound nicer :)
> README typo & other

- .travis.yml
- README.md
Let's add Travis to this project, and some badges
> Adds Travis and badges

- archey/archey.py
- test/test_archey_LAN_IP.py
- test/test_archey_LAN_IP_Automatic.py
- test/test_archey_LAN_IP_Manual.py
- test/test_archey_Model.py
- test/test_archey_Packages.py
> Fixes wrong mocked values & Implements skipped test cases

- README.md
> Package now available on PyPI and fixes instructions

- README.md
- archey/archey.py
Simple `try` .. `except` statement for Unicode encoding problems.
It avoids dumb crashes and _TraceBack_ when UTF8 is not handled.
With PuTTY (Windows) connected to a Debian server.
> Warns the user about problems with UTF8 encoding instead of crashing

- .github/ISSUE_TEMPLATE.md
- README.md
- archey/archey.py
- setup.py
- test/test_archey_CPU.py
Hi everyone !
Not much more than the title above.
* Debian 10
* Tests cases !
> CPU bug fix for some ARM architectures, documentation styles and version bumping

- archey/archey.py
fix some exception on Linux 4.14.52-rockchip armv7l, armbian,  tinkerboard
https://forum.armbian.com/topic/5169-tinker-board-thermals-broken-post-4120/
```bash
(venv) root@tinkerboard 15:15 /home/venv # archey
Traceback (most recent call last):
File "/home/venv/bin/archey", line 11, in <module>
sys.exit(main())
File "/home/venv/lib/python3.5/site-packages/archey/archey.py", line 1100, in main
output.append(key.name, key.value().value)
File "/home/venv/lib/python3.5/site-packages/archey/archey.py", line 771, in __init__
temp = float(file.read().strip()) / 1000
OSError: [Errno 22] Invalid argument
(venv) root@tinkerboard 15:15 /home/venv # cat /sys/class/thermal/thermal_zone1/temp
46363
(venv) root@tinkerboard 15:15 /home/venv # cat /sys/class/thermal/thermal_zone2/temp
cat: …
```
> fix error on Linux 4.14.52-rockchip armv7l, armbian,  tinkerboard

- archey/archey.py
- test/test_archey_lan_ip_manual.py
Sorry for the useless notifications folks ; I still can't figure why PyLint didn't report these warnings previously...
> [Hotfix] Travis : PyLint "useless-object-inheritance"

- README.md
- archey/archey.py
- test/test_archey_gpu.py
- test/test_archey_lan_ip_manual.py
- test/test_archey_temperature.py
Hey all,
I know the v4.5.0 went out not a long time ago but there were some stuffs I'd like to fix for the future.
* README (not relevant here)
* I've experienced a glitch yesterday with GPU info on an odd case, this should be fixed with the brought changes
* I've noticed we don't use the first value of a tuple on the very same class, so this has been removed as well
* :warning: **[WIP] There are some `ResourcesWarning` thrown during test cases. It would be cool if someone could look into it, in order to fix either Archey sources or its test cases as needed (I can't figure out a way to close the pending resources...).** :warning: 
Get the documentation and the test cases clean, improve performances and readability and handles new odd cases.
Debian, test cases...
> Various minor improvements 

- README.md
- archey/entries/temperature.py
- archey/test/test_archey_temperature.py
Hey there, it's me again. Today's concerns : **Temperature** entry.
Adds a proper `sensors` (LM-Sensors) usage to retrieve temperatures.
Fixes some documentation and test cases.
See #45.
@EntityCuber, could you review this and tell us whether it is OK for you now ?
Personal setup and test cases.
> Better temperature detection feature (closes #45)

- archey/singleton.py
- archey/test/test_archey_configuration.py
- archey/test/test_archey_output.py
- archey/test/test_archey_processes.py
- archey/test/test_archey_singleton.py
`Processes` & `Singleton` itself missed some proper test cases.
Adds some new tests and fixes `Configuration`'s ones.
Last parts of the code that weren't well-tested 😉
> Adds proper tests for singleton classes

- .travis.yml
- README.md
- archey/config.json
- archey/configuration.py
- archey/entries/lan_ip.py
- archey/entries/model.py
- archey/entries/packages.py
- archey/test/test_archey_lan_ip.py
- archey/test/test_archey_model.py
- archey/test/test_archey_packages.py
- archey/test/test_archey_wan_ip.py
Hey there o/
Before starting 2020, there are some changes that I wanted to bring for the v4.7.0.
**TL;DR**
* `LAN_IP` now allows IPv6 addresses hiding (`ip_settings.lan_ip_v6_support`) ;
* `systemd-detect-virt` is now being (optionally) used in `Model` ;
* `Packages` now supports `apt` for Debian-based distributions ;
* [BREAKING] `default_strings.bare_metal_environment` is not used anymore.
* All this code is now _much_ clean.
... ['cause it is OUR PROJECT](https://youtu.be/udBPW2rMQnc?t=19).
Unit tests + my laptop.
> `LAN_IP`, `Model` and `Packages` reworks

- LICENSE
Simple LICENSE file update.
GPLv3 was not detected on the project repository.
It has not, let's see if it works out.
> Updates the LICENSE file (to re-trigger Licensee hook)

- .gitattributes
- .travis.yml
- README.md
- packaging/after_install
- packaging/before_remove
- packaging/build.sh
- setup.py
Hey everyone :wave:
I thought that a new packages building process was required **before** drafting the v4.7.0, so here we are.
* Automation purposes
* Independence from @Xysto for RPM
* Consistency purposes (across different distributions)
* More complex process as Archey is now a Python module since #41
* Transparency purposes
> Additional note : I'll be still maintaining the [AUR package](https://aur.archlinux.org/packages/archey4/), as it's (still) on its way to the official Arch Linux repositories.
On my machine, maybe further improvements are to be made in the near future.
Any comment would be appreciated.
> Reworks (and publishes sources) of the packaging process

- archey/config.json
Being the great reviewer I am, this one slipped right past me and I merged #61 into master...
...sorry!
> [CONFIG] Modify `config.json` with proper defaults

- README.md
- archey.1
- archey/__main__.py
- archey/screenshot.py
- setup.py
Title should be self-explanatory :smile:
New CLI option/argument.
Implemented logic wants to be EAFP, handling many different cases in a "best-effort" fashion.
One may want to add its specific (omitted ?) program to the supported list (really easy).
:warning: Important note : Sometimes it's not possible to directly specify the output filename. In such cases, the targeted directory should be honored.
:warning: Important note (2) : This feature will be considered as a "soft-extension" of Archey, so no screenshot program has been (and will be) added to required/optional dependencies lists.
:warning: Important note (3) : It's a first very basic implementation, it might evolve in the future.
Thanks :bow:
Well, ScreenFetch supports it, and even some other Archey forks.
So I guess such a feature …
> [FEATURE] Implements a `-s` option to make Archey take a screenshot

- archey/screenshot.py
> Fixes a bug introduced in #75, released in v4.8.0
- ~~This pull request targets the `develop` branch~~ Hot-fix for v4.8 ;
> [SCREENSHOT] Fixes usages of unknown `.rpart` method

- archey/output.py
- archey/screenshot.py
- ~~This pull request targets the `develop` branch~~ Feature for the v4.8 ;
> [FEATURE] Exits with non-zero status code on Unicode or screenshot error

- archey/entries/model.py
- archey/test/entries/test_archey_model.py
If available, on GNU/Linux, adds hardware product "version" to `Model`.
Might be interesting.
Unit tests only.
- ~~This pull request targets the `develop` branch~~ Feature addressing the v4.8 ;
> [MODEL] Adds hardware product version if available

- README.md
- archey/entries/wan_ip.py
- archey/screenshot.py
- archey/test/entries/test_archey_uptime.py
- archey/test/entries/test_archey_wan_ip.py
- archey/test/test_archey_distributions.py
- config.json
+ Fixes IPv6 detection in some particular cases (behind a NAT46)
+ Speeds up `dig` usage failing when no IPv6 are available
+ DNS or HTTP external requests can now be disabled from configuration (closes #81)
+ DNS or HTTP resolvers can now be changed from configuration
+ Factorizes internal code to DRY
+ DNS and HTTP timeouts are now uncoupled and may be different
Bonus : Fixes some code styles issues found afterwards.
See #81.
Locally, and unit tests.
> [WAN_IP] Reworks for configuration, DRY and performance purposes

- README.md
- archey/entries/load_average.py
- archey/entries/model.py
- archey/entries/window_manager.py
- archey/test/entries/test_archey_load_average.py
- archey/test/entries/test_archey_model.py
- config.json
A few commits that fix some small bugs I've found in Archey.
Fixes the following issues:
- [Model] Prevents the vendor name being repeated when the product name already includes the vendor name, as on HP Laptops
- [Window Manager] Adds the Wayland variant of KWin to the process list
- [Load Average] Cuts off the load averages to 2 decimal places (configurable) in line with other tools like `uptime`
Tested on my systems and passes unit tests added & written
> Various small bugfixes

- archey/entries/uptime.py
- archey/test/entries/test_archey_uptime.py
`uptime` STDERR will now be read and each line will be emitted as a warning log. This allows macOS users experiencing "uptime: /dev/ttysXXX: No such file or directory" errors to silence them using configuration (instead of silently dropping them).
> closes #132
It hasn't (_EDIT_ on a affected macOS system).
> [UPTIME] Logs `uptime` errors at warning level

- README.md
- archey/entries/lan_ip.py
- archey/test/entries/test_archey_lan_ip.py
- config.json
> [LAN_IP] Allows link-local IP addresses hiding

- CHANGELOG.md
- README.md
- archey.1
- archey/__main__.py
- archey/logos/__init__.py
- archey/output.py
- archey/test/test_archey_logos.py
- archey/test/test_archey_output.py
See #158 for feature request.
> Note : `Output._distribution` protected attribute has been removed as actually unused.
Locally + unit tests.
> [OUTPUT] Implements "none" logo style to completely hide it
