HorlogeSkynet/archey4

- archey
If ```wmctrl``` is not installed, archey4 returns:
```bash
Traceback (most recent call last):
File "./archey", line 615, in <module>
output.append(key.name, key.value().value)
File "./archey", line 475, in __init__
self.value = wm or 'Not detected'
UnboundLocalError: local variable 'wm' referenced before assignment
```
This fixes the error by assigning "Not detected" in case ```wmctrl``` is not installed. 
It could be worth considering moving ```wmctrl``` to the list of required packages for ```archey4``` or using another method to determine the Windows Manager if this worka-round is sub-optimal.
> fix error if wmctrl is not installed

- README.md
- archey
- config.json
Adds a timeout option to `config.json` and `archey`. Now the user can set the desired timeout time in their `config.json` file.
For me, to get `WAN_IP` to populate successfully every time I run `archey` I required a timeout time (`timeout=5.0`) of `5.0`.
I tested this on my Arch Linux machine. Using timeout numbers like `0.5` `1` `1.0` all worked. 
Using timeout numbers like `.5` or `.any-valid-number` did **not** work.
> Add config options for timeout

- README.md
- archey
- config.json
Simply redirects `stderr` to `/dev/null` (or set it back to `STDERR` in function of `suppress_warning` configuration option value.
May be useful for some people 
On Debian Stretch, redirecting and setting back work like a charm
> Adds `suppress_warnings` option to configuration

- archey/archey.py
Added support for the filesystem used by Windows Subsystem for Linux filesystem.
Originally submitted here https://github.com/djmelik/archey/pull/45
nb: the User will still need to either cat /proc/self/mounts > /etc/mtab or create a symlink
Allows archey to be used with WSL distro's
Locally tested
> Add Support for WSL Distros

- .github/ISSUE_TEMPLATE.md
- README.md
- archey/archey.py
- test/test_archey_temperature.py
Simple conditional string concatenation which adds the `Max.` temperature detail if there are more than one value retrieved.
> I also added an entry for Python version to the issue template, for debugging and helping purposes.
Bye :wave:
When the device got only one temperature value, there is no need to compute and show the maximum.
This is still contestable and open for debate !
> Hide `Max.` temperature when there is only one value

- test/test_archey_lan_ip_manual.py
- test/test_archey_model.py
CI failed yesterday.
The [v2.3.0 of Pylint has added `no-else-raise` rule](https://github.com/PyCQA/pylint/pull/2636), causing the CI to fail on test cases yesterday, after a README edition.
Locally + Travis.
> Fixes CI by dealing with Pylint `no-else-raise` rule, now fixed

- archey/processes.py
See PyCQA/pylint#3062.
According to [the documentation](https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module), constants from the Python's `site` module shouldn't be used in programs.
I took the opportunity to set a non-OK exit code (`1`) when the `ps` program is not available.
> Replaces Python site's `exit` by `sys.exit`

- README.md
- archey/entries/wan_ip.py
- archey/test/test_archey_wan_ip.py
Hey all :wave:
Explanations below :
This patch replaces old `wget` sub-calls by `urllib.request` usages (that should be consistent across Python 3.X versions).
README has also been updated and now accounts for **WAN\_IP** external connections attempts.
Keeping `wget` sub-call as an optional dependency is actually weird and useless, as Python 3.X standard library allows us to perform HTTP requests easily.
Personal setup and test cases.
> Replaces `wget` fall-back call by a proper `urllib.request` usage

- README.md
- archey/configuration.py
- archey/entries/disk.py
- archey/entries/ram.py
- archey/test/test_archey_disk.py
- archey/test/test_archey_ram.py
A minor change that allows the warning and danger thresholds of the disk and ram sections to be configurable.
Different users have different opinions on when they would like to be warned about disk/ram usage.
On my arch linux system.
> Allow configurable thresholds for disk and ram warning/danger colors.

- archey/entries/disk.py
- archey/test/test_archey_configuration.py
- archey/test/test_archey_disk.py
See #42 for the rationale.
EDIT : I've given up the `/` solution as it would omit all the other **local** mount points as well, and against systems with a `/home` larger than `/` (for instance), it wouldn't be relevant at all.
:warning: Not tested on a real BTRFS system. :warning:
@qx071, are you ready to test / improve / guide me on this ?
---
**EDIT 2019-08-15** : I've figured out that the `btrfs [...]` call being made does not work at all.
So @qx071, I'll definitely need you to properly list BTRFS (sub-)volumes to fetch their meta-data. Waiting for your input on this !
**EDIT 2019-12-24** : To myself (@HorlogeSkynet), don't forget to rename `self.usage` to `self._usage`.
**EDIT 2020-03-25** : Wrong `btrfs` call has been replaced, it _should_ work as expected now.
---
> Feature / Bugfix : Proper BTRFS support

- packaging/build.sh
See #59.
Multiple RPMs will now be generated, named as : `archey4-4.Y.Z-R.py3.V.noarch.rpm` (with `V` the second segment of a Python version).
Users will **HAVE TO** pick the correct package according to their Python 3 environment.
Docker containers for each affected distribution.
> [PACKAGING] Fix FPM-based installation location

- README.md
- archey/entries/disk.py
- archey/test/test_archey_disk.py
- packaging/build.sh
This PR allows the inclusion of btrfs filesystems in the disk space module without root, and fixes the behaviour of the btrfs implementation.
Current behaviour is incorrect for btrfs filesystems:-
* Usage shown is actually allocated space on disk (this allocated space can be larger than the amount of data stored in it, or can be empty if files have been removed)
* Usage and total filesystem space available are counted multiple times for some btrfs configurations, e.g. a RAID-1 setup.
* Root is required to use the current `btrfs-progs` utilities (not ideal!)
* Using the python tests.
* Using two machines with different btrfs configurations.
> [DISK] BTRFS implementation fixes

- archey/entries/uptime.py
- archey/processes.py
- archey/test/test_archey_uptime.py
On some systems without read permissions on `/proc/uptime` (e.g. Android), or lacking `/proc/uptime` (BSD) Archey will fail with a traceback. This PR fixes this bug and adds additional fallback detections to the Uptime entry to support these systems.
Reworked the uptime entry somewhat to now try a few methods of detecting uptime, hopefully preventing complete failure with a traceback.
The uptime is now found as follows:
* Try reading /proc/uptime
* Try using the clocks provided by Python's `time` module for Linux, macOS and BSD.
* Try parsing the `uptime` command (from `procps`(`-ng`)
Added test cases for this new behaviour, as well as getting `uptime` output from various systems and making sure these are all handled correctly.
Using the test cases with various different systems' …
> [BUGFIX] Fix crash if no read permissions for /proc/uptime, and use fallbacks instead

- README.md
- archey/config.json
- archey/configuration.py
- archey/entries/gpu.py
- archey/entry.py
- archey/output.py
- archey/test/test_archey_gpu.py
- archey/test/test_archey_output.py
Closes #61.
GPUs were not following `3D` > `VGA` > `Display` order (poor implementation), and only one was displayed.
This should be fixed now.
See #61.
Test cases.
> [GPU] Adds support for multiple GPUs (and fixes their display order)

- archey/entries/terminal.py
- archey/test/test_archey_terminal.py
Closes #65.
Simple patch implementing an automatic and manual detection of terminal emulators.
One may easily add support for another emulator by adding `X_EMULATOR_SPECIFIC_ENV_VAR` --> `Terminal Emulator Name` association to the current list.
See #65 for rationale.
Test cases + my system.
> [TERMINAL] Improves terminal detection based on environment variables

- README.md
- archey/__main__.py
- archey/config.json
- archey/configuration.py
This patch is mainly inspired from the work of @ingrinder (see `2bbc2dae`).
You may notice an execution up to twice as fast.
This new behavior could be disabled with the new `parallel_loading` configuration option.
See #68.
Locally & test cases.
- ~~[ ] \[IF NEEDED\] I have updated the test cases (which pass) accordingly ;~~
> [FEATURE] Makes entries being loaded in parallel

- README.md
- archey/config.json
- archey/configuration.py
- archey/entries/disk.py
- archey/test/test_archey_disk.py
- packaging/build.sh
Yet more rewriting code! 😨 
This is a full rework of the `Disk` entry in an effort to implement #55 and fix #62. It may also potentially be faster as it relies on only a single call to `df` for input, and nothing else. 
This also additionally fixes an (unreported) bug, where we don't actually calculate the correct space usage in `Disk` currently... oops!
It seems to work fine so far... Some tests have been written for the new functionality, some are TBC. (**This section to be completed properly before converting to a full PR 😁**)
@HorlogeSkynet Could you let me know what you think of this approach? I'm up for changing it but basing all of our calculations around a single basic `df` call like this is what I came up with after some thinking on how to approach reworking this entry. TIA! …
> [WIP] Disk entry rework

- archey/entries/packages.py
- archey/test/entries/test_archey_packages.py
Simply adds the OpenBSD and FreeBSD package managers to the entry so it works.
See #69.
On fresh virtual machines.
> [PACKAGES] Add support for FreeBSD & OpenBSD

- archey/colors.py
- archey/entries/terminal.py
- archey/test/entries/test_archey_terminal.py
- archey/test/test_archey_colors.py
- archey/test/test_archey_output.py
This patch suppresses colors from text output when `NO_COLOR` environment variable is set.
See <https://no-color.org/>.
```bash
python3 -m unittest
NO_COLOR=1 python3 -m unittest
```
> [FEATURE] Honors `NO_COLOR` when set

- README.md
- archey/__main__.py
- archey/config.json
- archey/constants.py
- archey/entries/disk.py
- archey/entries/distro.py
- archey/entries/gpu.py
- archey/entries/lan_ip.py
- archey/entries/model.py
- archey/entries/ram.py
- archey/entries/temperature.py
- archey/entries/terminal.py
- archey/entries/wan_ip.py
- archey/entry.py
- archey/output.py
- archey/test/entries/__init__.py
- archey/test/entries/test_archey_disk.py
- archey/test/entries/test_archey_gpu.py
- archey/test/entries/test_archey_lan_ip.py
- archey/test/entries/test_archey_model.py
- archey/test/entries/test_archey_ram.py
- archey/test/entries/test_archey_temperature.py
- archey/test/entries/test_archey_terminal.py
- archey/test/entries/test_archey_wan_ip.py
- archey/test/test_archey_entry.py
- archey/test/test_archey_output.py
This PR is is to enable configuration rearrangement, as in #57.
Apologies that this is in the form of a single squashed commit... however I rebased this branch quite a lot of times and the history was a mess, so it got squashed into one.
While I've provided an implementation here, if you don't think it's suitable we can also use this PR to discuss an alternative.
See #57.
* Configuration completely rearranged.
* Entries are now specified as `dict`s containing their `type` and ~~`options` keys~~ respective options.
* All entry-specific options are in the entry's definition thing.
* Entries can be specified multiple times with different options as a side-effect of this. I may or may not have a plan to try out custom-defined entries with this... 😆 
* All `Entry` subclasses now have …
> [FEATURE] [BREAKING] Change configuration layout

- README.md
- archey/entries/cpu.py
- archey/entries/gpu.py
- archey/test/entries/test_archey_cpu.py
- archey/test/entries/test_archey_gpu.py
- config.json
This is an API-breaking change.
Now multiple CPUs should be supported, and number of cores per CPU will be shown by default.
> Below examples show output changes for a dual CPUs setup (respectively with `N` & `M` cores).
Text output change :
```diff
- CPU: A-CPU-MODEL-NAME_1
+ CPU: N x A-CPU-MODEL-NAME_1, M x A-CPU-MODEL-NAME_2
```
JSON API change :
```diff
- "CPU": "A-CPU-MODEL-NAME_1",
+ "CPU": [
+     {"A-CPU-MODEL-NAME_1": N},
+     {"A-CPU-MODEL-NAME_2": M}
+ ],
```
See also new `one_line` & `show_count` options available for `CPU` entry type.
It appears Archey does not support multiple CPUs (only the first one would be displayed).
Additionally, adding the number of cores may be relevant.
See also <https://github.com/dylanaraps/neofetch/issues/1467> partially related.
(@Nalorokk's …
> [CPU] [FEATURE/BREAKING] Multiple CPUs support

- .github/workflows/integration.yml
- README.md
- archey/configuration.py
- archey/entries/disk.py
- archey/entries/temperature.py
- archey/test/entries/test_archey_cpu.py
- archey/test/entries/test_archey_disk.py
- archey/test/entries/test_archey_hostname.py
- archey/test/entries/test_archey_lan_ip.py
- archey/test/entries/test_archey_model.py
- archey/test/entries/test_archey_ram.py
- archey/test/entries/test_archey_uptime.py
- archey/test/test_archey_output.py
- archey/test/test_archey_processes.py
- packaging/build.sh
- setup.py
Drop Python 3.4 support and removes code addressing particular old behaviors.
Python 3.4 is EOL for a while now, and dropping it allows us to move forward.
CI.
> [META] Drops support for Python 3.4 (EOL)

- .github/workflows/integration.yml
- packaging/build.sh
- setup.py
Python 3.10 is out, we should test Archey against it.
Thanks to CI, one day, maybe.
> ~~:warning: Build is currently broken due to one of Pylint's depedencies.  
> `lazy-object-proxy` requires a Wheel to be built, but due to pypa/wheel#354 (see also pypa/packaging#308 & <https://bugs.python.org/issue40747>), the operation fails.  
> Currently keeping this PR as draft while waiting for the fix (python/cpython#20333 or python/cpython#22858) to be accepted.~~
> Pylint and Pyinstaller have been disabled in CI though (not yet compatible).
- \[IF NEEDED\] I have updated the _README.md_ file …
> [META] Adds official support for Python 3.10

- README.md
- archey/api.py
- archey/configuration.py
- archey/entries/kernel.py
- archey/test/entries/__init__.py
- archey/test/entries/test_archey_kernel.py
- archey/test/test_archey_api.py
- archey/test/test_archey_colors.py
- archey/test/test_archey_configuration.py
- archey/test/test_archey_distributions.py
- archey/test/test_archey_logos.py
- archey/test/test_archey_output.py
- archey/test/test_archey_processes.py
- archey/test/test_archey_singleton.py
- archey/test/test_archey_utility.py
- archey/test/test_archey_version.py
- archey/utility.py
- config.json
My changes add an entry file which queries kernel.org for the latest stable kernel version.
`archey/entries/kernel_latest` - entry class 
`archey/__main__` - added import for `kernel_latest` and subsequently to the `Entries` enum
`setup.py` - I'm lazy and I used python `requests` (Sorry if I should've used a builtin, that can change?)
I saw that kernel.org has metadata for latest kernel, and I think it's neat to see how out of date (or not?) your distribution's kernel is.
Only tested on my Arch machine. However, I can't think of any way it would cause issues.
*TODO* I don't really know how to write tests, so my pull doesn't include one.
(The only issue would be if the host doesn't have a connection, but I think the other net related ones also fail unsafely?)
- Bug fix (non-breaking change …
> [KERNEL] Implement kernel release comparison against <www.kernel.org>

- .github/workflows/integration.yml
- README.md
- archey/entries/temperature.py
- archey/test/entries/test_archey_temperature.py
- config.json
> closes #107
See #107 for rationale.
Some chipset subfeatures may return inaccurate values when probed.
Unit test.
> [TEMPERATURE] Adds `sensors_excluded_subfeatures` config. option

- CHANGELOG.md
- README.md
- archey/__main__.py
- archey/configuration.py
- archey/entries/custom.py
- archey/test/entries/test_archey_custom.py
This patch brings a first support for "custom entries" to Archey. It
mainly allows users to run custom commands through their configuration
file.
In order to give "power to the user" for most of situations:
* STDERR output **MAY** be silenced through `log_stderr` option
* command exit status code **MAY** be ignored through `check` option
Multi-lines results will be joined on the same line, unless `one_line`
option is disabled.
Users **SHOULD** only enable `shell` option if they have to.
> See #111 for rationale.
> [CORE] Adds support for custom entries

- archey/entries/cpu.py
- archey/entries/model.py
- archey/entries/ram.py
- archey/test/entries/test_archey_cpu.py
- archey/test/entries/test_archey_model.py
- archey/test/entries/test_archey_ram.py
Hi,
I created a new port [sysutils/archey4](https://github.com/freebsd/freebsd-ports/commit/3be095c9e4fdb811ac3303d1b9a52487278e96ce) in our FreeBSD catalog ports tree. It contains all the patches I wrote to add support for the FreeBSD operating systems.
I added the 3 commits to solve the entries detection for the following:
- RAM memory
- CPU
- model
Missing entries not detected before these patches
FreeBSD 14.0-CURRENT (development release) and FreeBSD 13.1-RELEASE (latest stable release)
> Add support for FreeBSD

- archey/entries/disk.py
- archey/test/entries/test_archey_disk.py
Replaces entries of APFS volumes with an aggregated entry for that volume's container.
See #115.
> [DISK] Fixes overcounting of APFS on macOS

- archey/__main__.py
For users not using a configuration file, `available_entries` was built with a `Custom` entry lacking of required `command` field.
See #120.
On GNU/Linux.
> [CORE][FIX] Silences warning about broken `Custom` entry

- README.md
- archey/output.py
- archey/test/test_archey_output.py
- config.json
Adds a configuration option for the preferred logo style
A few simple changes to `Output` to allow this.
Feature addition by request :smiley:
Setting distribution to Darwin and specifying the option seems to work for me. Also worked when I added a placeholder extra logo for my own distro and specified it as a style.
> [Output] Adds configuration option for preferred logo style

- archey/logos/moevalent.py
- archey/logos/univalent.py
Corrected the blank positions on the bottom two lines of the Univalent and Moevalent logos. (Please forgive me to post continuously.)
The bottom two lines of the logos were shifted to the left by one half-pitch character, so I corrected it.
The correct spacings were missing to properly align with the rest of the lines.
As usual, operation tests were conducted on both a virtual machine and a real one, but no problems were found.
> correct spacing issue on univalent & moevalent logo

- archey/entries/wan_ip.py
- archey/test/entries/test_archey_wan_ip.py
This is just a small change so that if `dig` returns a nonzero exit code, then we don't immediately return `None` as the IP.
For example on my home network I block outgoing port 53:
As you see in this case archey fails to get the IP with the default settings and doesn't fall back to the configured HTTP URL :frowning_face:
It now gets my IP and passes the additional test case I added
> [WAN_IP] Fall back to HTTP properly on DNS connection errors

- archey/logos/darwin.py
A copy of the Darwin `RETRO` logo with a different (non-bright) color set.
`RETRO` looks broken on my terminal.
> [LOGO] Add Darwin retro low-intensity logo

- .github/workflows/integration.yml
- README.md
> [BUILDING] Add doc. and CI steps for standalone building with Nuitka

- archey/test/entries/test_archey_terminal.py
Pretty simple bugfix - I noticed this test has been failing on my system so I don't have the latest Archey version! :scream: 
`s/archey.colors.Colors/archey.colors.Style` in `test_archey_terminal.py`
:smiley: 
It makes the test pass!
- ~~\[IF NEEDED\] I have updated the _README.md_ file accordingly ;~~
- ~~\[IF BREAKING\] This pull request targets next Archey version branch ;~~
> [Bug/Tests] Fix Terminal entry test

- CHANGELOG.md
- archey/entries/window_manager.py
- archey/test/entries/test_archey_window_manager.py
See #142.
Unit tests and locally (Debian 11).
> [WINDOW_MANAGER] Adds display server protocol to entry

- README.md
- archey/configuration.py
- archey/entries/cpu.py
- archey/entries/custom.py
- archey/entries/desktop_environment.py
- archey/entries/disk.py
- archey/entries/distro.py
- archey/entries/gpu.py
- archey/entries/hostname.py
- archey/entries/kernel.py
- archey/entries/lan_ip.py
- archey/entries/load_average.py
- archey/entries/model.py
- archey/entries/packages.py
- archey/entries/processes.py
- archey/entries/ram.py
- archey/entries/shell.py
- archey/entries/temperature.py
- archey/entries/terminal.py
- archey/entries/uptime.py
- archey/entries/user.py
- archey/entries/wan_ip.py
- archey/entries/window_manager.py
- archey/entry.py
- archey/test/entries/test_archey_lan_ip.py
- archey/test/entries/test_archey_terminal.py
- config.json
Possibly all of them have now worked:
Please have a look there:
#141
> [CORE] Adds (Nerd Fonts) icons for entries

- CHANGELOG.md
- COPYRIGHT.md
- archey/logos/rhel.py
The default logo for RHEL has been changed to the new logo "the hat". The previous logo is sill available as alternate logo `shadowman` 
- Implementation of the the new logo
- renaming the previous logo to LOGO_SHADOWMAN
- Providing alias for the current logo as LOGO_HAT
Cosmetic reasoons :-)
Visually tested using following commands:
python3 -m archey -d rhel 
python3 -m archey -d rhel -l shadow man
on a Mac (macOS 13.6.3 x86_64; Darwin 22.6.0) from macOS terminal as well as from inside VSCode.
> Changes default Red Hat (rhel) logo to current logo "The hat"

- archey/entries/gpu.py
- archey/test/entries/test_archey_gpu.py
Fix for #149.
Parse `lspci -m` (ie machine readable format) to only match on the PCI class rather than the entire vendor + product string.
See #149 :grin: 
Seems to work fine on my systems, modified tests pass.
> [GPU] Parses `lspci` to avoid classing 3D NAND devices as GPUs.

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
- README.md
- apparmor.profile
- packaging/after_install
- packaging/after_remove
- packaging/before_remove
- packaging/build.sh
:warning: TODO :
This patch provides a first AppArmor profile candidate to be included in Archey GNU/Linux distribution packages.
See <https://apparmor.net/>.
Debian 11.
- My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).
> [PACKAGING] Provides a dedicated AppArmor profile

- README.md
- apparmor.profile
- archey/entries/packages.py
- archey/test/entries/test_archey_packages.py
- config.json
This PR changes the output provided by dividing the number of installed packages by package managers. It also adds support for ```flatpak``` and ```snap``` package count.
These changes allow to count ```flatpak``` and ```snap``` packages, also changing the total package count, moving from a total number to more precise data, showing the number of packages for each available package manager.
Example:
```
User: username
Hostname: hostname
Model: machine_model
..vvAAAvv..               Distro: Ubuntu 22.04.4 LTS x86_64
.:s/OOOOOOOOOOOOO\s:.          Kernel: Linux 6.8.0
.sOOOOOOOOOOOOOO.vv.OOOs.        Uptime: 3 minutes
.sOOOOOOOOO,ssssn:lMMl:OOOOs.      Load Average: 0.07 0.12 0.09
:OOOOOOO.n@'MMMMMMy\^^/.OOOOOO:     Processes: 168
:OOOOOOOiMMj@"OOOO"YIOOIlOOOOOOO:    Window Manager: Not …
```
> Show packages count divided by package manager

- CHANGELOG.md
- apparmor.profile
- archey/entries/gpu.py
- archey/test/entries/test_archey_gpu.py
See #130.
Unit tests and Raspberry Pi 1 (running as root).
-  Bug fix (non-breaking change which fixes an issue)
> [GPU] Adds support for Raspberry Pi (VideoCore chipsets)
